@startuml CL_Envelope
' requirement REQ-00001-1
' requirement REQ-00006-1

!startsub Envelope

namespace grammar.envelope {
  class "<<module>>" as Envelope {
    + source_file
    + diagram
    + comment
    + block_comment
  }
}

!endsub

@enduml
