@startuml CL_SequenceChapter
' requirement REQ-00017-1
' requirement REQ-00018-1
' requirement REQ-00019-1
' requirement REQ-00025-1

!startsub SequenceChapter

namespace grammar.sequence {
  class "<<module>>" as SequenceChapter {
    + participant_declaration
    + frame_block
    + else_clause
    + divider
  }
}

!endsub

@enduml
